spring.application.name=rate-printer
server.port=8081

spring.cloud.zookeeper.connect-string=localhost:2181

management.endpoints.web.exposure.include=health,info,prometheus

management.metrics.tags.application=${APP_METRICS_LABEL:client}

app.client-id=${APP_CLIENT_ID:client}
