spring.application.name=rate-printer
server.port=8081
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
spring.profiles.default=dev

management.endpoints.web.exposure.include=health,info,prometheus

management.metrics.tags.application=${APP_METRICS_LABEL:client}

app.client-id=${APP_CLIENT_ID:client}
